[package]
name = "ITP-2019"
version = "0.1"
lean_version = "nightly-2019-01-13"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover-community/mathlib", branch = "library_search", rev = "d244687793dd9d364d55579f4a0ce6c71597e644"}
