[package]
name = "ITP-2019"
version = "0.1"
lean_version = "3.4.2"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover-community/mathlib", branch = "master", rev = "00aaf05a00b928ea9ac09721d87ae5d2ca1ae5a1"}
